// Generated by CoffeeScript 1.6.2
var Arcball, Color, Cube, Mesh, PerspectiveCamera, Scene, Test, pex, _ref;

pex = pex || require('./lib/pex');

_ref = pex.scene, Scene = _ref.Scene, PerspectiveCamera = _ref.PerspectiveCamera, Arcball = _ref.Arcball;

Mesh = pex.gl.Mesh;

Cube = pex.geom.gen.Cube;

Test = pex.materials.Test;

Color = pex.color.Color;

pex.require(['utils/GLX', 'ucc/Layer'], function(GLX, Layer) {
  return pex.sys.Window.create({
    settings: {
      width: 1280,
      height: 720,
      fullscreen: pex.sys.Platform.isBrowser
    },
    init: function() {
      this.camera = new PerspectiveCamera(60, this.width / this.height);
      this.arcball = new Arcball(this, this.camera);
      this.scene = new Scene();
      this.scene.add(new Mesh(new Cube(), new Test()));
      return this.glx = new GLX(this.gl);
    },
    draw: function() {
      this.glx.enableDepthWriteAndRead(true, true).clearColorAndDepth(Color.Black);
      return this.scene.draw(this.camera);
    }
  });
});
