// Generated by CoffeeScript 1.6.2
var __hasProp = {}.hasOwnProperty,
  __extends = function(child, parent) { for (var key in parent) { if (__hasProp.call(parent, key)) child[key] = parent[key]; } function ctor() { this.constructor = child; } ctor.prototype = parent.prototype; child.prototype = new ctor(); child.__super__ = parent.prototype; return child; };

define(function(require) {
  var Layer, Mesh, Plane, Texture2D, Textured, _ref;

  _ref = require('pex/gl'), Mesh = _ref.Mesh, Texture2D = _ref.Texture2D;
  Plane = require('pex/geom/gen').Plane;
  Textured = require('pex/materials').Textured;
  return Layer = (function(_super) {
    __extends(Layer, _super);

    function Layer(imageFile) {
      var geom, material,
        _this = this;

      geom = new Plane(1, 1, 1, 1, 'x', 'z');
      material = new Textured();
      Layer.__super__.constructor.call(this, geom, material);
      material.uniforms.texture = Texture2D.load(imageFile, function(e) {
        console.log(e.height / e.width);
        _this.scale.set(1, 1, e.height / e.width);
        return console.log(e.width, e.height);
      });
    }

    return Layer;

  })(Mesh);
});
